r"""
Creates starter templates in %APPDATA%\PaperGen\templates\
Run once to generate: mla.docx, turabian.docx, mla.typ, turabian.tex

For .typ and .tex, open the generated file and write your paper body
below the marked section. The header metadata is pre-filled by PaperGen.
"""

import os
from pathlib import Path
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

TEMPLATES = Path(os.environ.get("APPDATA", Path.home())) / "PaperGen" / "templates"
TEMPLATES.mkdir(parents=True, exist_ok=True)


# ── Word templates ────────────────────────────────────────────────────────────
def make_mla_docx():
    doc = Document()
    section = doc.sections[0]
    section.top_margin = section.bottom_margin = Inches(1)
    section.left_margin = section.right_margin = Inches(1)

    style = doc.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)

    def add(text="", align=WD_ALIGN_PARAGRAPH.LEFT, bold=False):
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after  = Pt(0)
        p.paragraph_format.line_spacing = Pt(24)
        p.alignment = align
        run = p.add_run(text)
        run.bold = bold
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)
        return p

    add("{{your_name}}")
    add("{{professor_name}}")
    add("{{class_full}}")
    add("{{due_date}}")
    add("{{paper_title}}", align=WD_ALIGN_PARAGRAPH.CENTER)
    add()
    add("Begin your paper here.")

    out = TEMPLATES / "mla.docx"
    doc.save(str(out))
    print(f"Created: {out}")


def make_turabian_docx():
    doc = Document()
    section = doc.sections[0]
    section.top_margin = section.bottom_margin = Inches(1)
    section.left_margin = section.right_margin = Inches(1)

    style = doc.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)

    def add(text="", align=WD_ALIGN_PARAGRAPH.LEFT, bold=False, size=12):
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after  = Pt(0)
        p.paragraph_format.line_spacing = Pt(24)
        p.alignment = align
        run = p.add_run(text)
        run.bold = bold
        run.font.name = "Times New Roman"
        run.font.size = Pt(size)
        return p

    for _ in range(12):
        add()
    add("{{paper_title}}", align=WD_ALIGN_PARAGRAPH.CENTER, bold=True, size=14)
    add()
    add()
    add("{{your_name}}",   align=WD_ALIGN_PARAGRAPH.CENTER)
    add("{{class_full}}", align=WD_ALIGN_PARAGRAPH.CENTER)
    add("{{school}}",      align=WD_ALIGN_PARAGRAPH.CENTER)
    add("{{professor_name}}", align=WD_ALIGN_PARAGRAPH.CENTER)
    add("{{due_date}}",    align=WD_ALIGN_PARAGRAPH.CENTER)

    doc.add_page_break()
    add("Begin your paper here.")

    out = TEMPLATES / "turabian.docx"
    doc.save(str(out))
    print(f"Created: {out}")


# ── Typst templates ───────────────────────────────────────────────────────────
def make_mla_typ():
    content = r"""// MLA paper — generated by PaperGen
// Requires: typst init @preview/modern-mla (or install via Typst app)
// Compile with: typst compile this-file.typ

#import "@preview/modern-mla:0.1.0": *

#show: mla.with(
  title: "{{paper_title}}",
  author: "{{your_name}}",
  professor: "{{professor_name}}",
  course: "{{class_full}}",
  date: datetime.today(),
)

// ── Begin writing below ───────────────────────────────────────────────────────

Your introduction goes here.
"""
    out = TEMPLATES / "mla.typ"
    out.write_text(content, encoding="utf-8")
    print(f"Created: {out}")


def make_turabian_typ():
    content = r"""// Turabian/Chicago paper — generated by PaperGen
// No external package required; formatting is manual below.
// Compile with: typst compile this-file.typ

#set page(paper: "us-letter", margin: 1in)
#set text(font: "Times New Roman", size: 12pt)
#set par(leading: 1em, first-line-indent: 0.5in)

// ── Title page ────────────────────────────────────────────────────────────────
#align(center)[
  #v(3in)
  *{{paper_title}}*

  #v(1in)
  {{your_name}} \
  {{class_full}} \
  {{school}} \
  {{professor_name}} \
  {{due_date}}
]

#pagebreak()

// ── Begin writing below ───────────────────────────────────────────────────────

Your introduction goes here.
"""
    out = TEMPLATES / "turabian.typ"
    out.write_text(content, encoding="utf-8")
    print(f"Created: {out}")


# ── LaTeX templates ───────────────────────────────────────────────────────────
def make_turabian_tex():
    content = r"""% Turabian/Chicago paper — generated by PaperGen
% Requires: turabian-formatting package (on CTAN, included in TeX Live / MiKTeX)
% Compile with: pdflatex this-file.tex (twice for page numbers)

\documentclass{turabian-researchpaper}
\usepackage[utf8]{inputenc}
\usepackage{csquotes, ellipsis}
\usepackage[pass, letterpaper]{geometry}

% For footnote citations + bibliography, uncomment:
% \usepackage{biblatex-chicago}
% \addbibresource{works-cited.bib}

\title{{{paper_title}}}
\author{{{your_name}}}
\course{{{class_full}}}
\institution{{{school}}}
\date{{{due_date}}}

\begin{document}
\maketitle

% ── Begin writing below ───────────────────────────────────────────────────────

Your introduction goes here.

% \printbibliography  % uncomment if using biblatex-chicago

\end{document}
"""
    out = TEMPLATES / "turabian.tex"
    out.write_text(content, encoding="utf-8")
    print(f"Created: {out}")


def make_mla_tex():
    content = r"""% MLA paper — generated by PaperGen
% Standard MLA formatting via geometry + setspace.
% Compile with: pdflatex this-file.tex

\documentclass[12pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{setspace}
\usepackage{fancyhdr}
\usepackage{times}

\doublespacing

\pagestyle{fancy}
\fancyhf{}
\rhead{{{name_last}} \thepage}
\renewcommand{\headrulewidth}{0pt}

\begin{document}

\begin{flushleft}
{{your_name}} \\
{{professor_name}} \\
{{class_full}} \\
{{due_date}}
\end{flushleft}

\begin{center}
{{paper_title}}
\end{center}

% ── Begin writing below ───────────────────────────────────────────────────────

Your introduction goes here.

\begin{center}
Works Cited
\end{center}

% Add your works cited entries here.

\end{document}
"""
    out = TEMPLATES / "mla.tex"
    out.write_text(content, encoding="utf-8")
    print(f"Created: {out}")


if __name__ == "__main__":
    make_mla_docx()
    make_turabian_docx()
    make_mla_typ()
    make_turabian_typ()
    make_turabian_tex()
    make_mla_tex()
    print(f"\nDone. Templates in: {TEMPLATES}")