// MLA paper — generated by PaperGen
// Requires: typst init @preview/modern-mla (or install via Typst app)
// Compile with: typst compile this-file.typ

#import "@preview/modern-mla:0.1.0": *

#show: mla.with(
  title: "{{paper_title}}",
  author: "{{your_name}}",
  professor: "{{professor_name}}",
  course: "{{class_full}}",
  date: datetime.today(),
)

// ── Begin writing below ───────────────────────────────────────────────────────

Your introduction goes here.
