// Turabian/Chicago paper — generated by PaperGen
// No external package required; formatting is manual below.
// Compile with: typst compile this-file.typ

#set page(paper: "us-letter", margin: 1in)
#set text(font: "Times New Roman", size: 12pt)
#set par(leading: 1em, first-line-indent: 0.5in)

// ── Title page ────────────────────────────────────────────────────────────────
#align(center)[
  #v(3in)
  *{{paper_title}}*

  #v(1in)
  {{your_name}} \
  {{class_full}} \
  {{school}} \
  {{professor_name}} \
  {{due_date}}
]

#pagebreak()

// ── Begin writing below ───────────────────────────────────────────────────────

Your introduction goes here.
